language: ruby

sudo: false

branches:
  only:
  - master

rvm:
  - 2.4.0

services:
  - mongodb

install:
  - bundle install

before_script:
  - mongo segmentation-api-test --eval 'db.addUser("travis", "test");'

script:
  - bundle exec rake

cache: bundler
